language: node_js

node_js:
  - "0.10"

before_script:
  - mysql -e 'create database wejs;'
  - npm install -g bower
  - bower install
  - cp config/local.example config/local.js

services:
  - mysql
  - mongodb
  - redis-server

notifications:
  email:
    - alberto.souza.99@gmail.com
    - saviogl@gmail.com